# DataSource Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    username: root
    password: root123456
  thymeleaf:
    cache: false
    prefix: classpath:templates/html/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  resources: classpath:/static/**

#服务器设置
server:
  port: 8080
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 50Mb

#日志设置
logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: debug
    com.howtodoinjava: INFO
    org.hibernate: ERROR
#最大连接数
http:
  maxTotal: 100
#并发数
  defaultMaxPerRoute: 20
#创建连接的最长时间
  connectTimeout: 1000
#从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
#数据传输的最长时间
  socketTimeout: 10000
#提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true